summary: XML-based font configuration tools
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.15.0
bin-url: https://github.com/leleliu008/uppm-package-repository-android-30-aarch64/releases/download/2025.01.23/fontconfig-2.15.0-android-30-arm64-v8a.release.tar.xz
bin-sha: 6b8b7199fc285689ffc749a6e538625e0e875e017efad3702bd2b12844eb1d6f
